### ISSUE TITLE
How to change font for the axis?

### ISSUE THREAD

**Issue by DjayDev** [HanSolo/charts#13]
Hello @HanSolo ,

I try to change the font for the axis but it's not working for the moment (I've tried through css).
![image](https://user-images.githubusercontent.com/7959058/41783308-dafafcc2-763c-11e8-8ce6-95686c031c53.png)
```css
.axis .yaxis {
    -fx-font-family: "Arial";
    -fx-font-size: 18px;
}
```

I could change the size with the `setAutoFontSize(false)` and `setTickLabelFontSize()` methods but I would like to change the font also.

Do you have a sample on how to change it for the axis on a simple XYChart ?

Thanks,
Gerald
